const Orders=[
    {
        productName:'Powder',
        ProductNumber:'4',
        paymentStatus:'Due',
        shipping:'pending'
    },

    {
        productName:'Powder',
        ProductNumber:'4',
        paymentStatus:'Due',
        shipping:'pending'
    },
    {
        productName:'Powder',
        ProductNumber:'4',
        paymentStatus:'Due',
        shipping:'pending'
    },
    {
        productName:'Powder',
        ProductNumber:'4',
        paymentStatus:'Due',
        shipping:'pending'
    },
    {
        productName:'com',
        ProductNumber:'2',
        paymentStatus:'Refunded',
        shipping:'Declined'
    },
    {
        productName:'fridge',
        ProductNumber:'3',
        paymentStatus:'Due',
        shipping:'pending'
    },
    {
        productName:'washingMC',
        ProductNumber:'8',
        paymentStatus:'paid',
        shipping:'Delivered'
    },
    {
        productName:'gold',
        ProductNumber:'9',
        paymentStatus:'Due',
        shipping:'pending'
    },
    {
        productName:'Powder',
        ProductNumber:'10',
        paymentStatus:'Due',
        shipping:'pending'
    }

]